#!/usr/bin/python
from gdscript_docs_tools import *

if __name__ == "__main__":
	args = {}
	get_argv(args)
	# print(args)

	if args["help"]:
		print(
			"""
			md2gds_docs version 1.0
			It is a simple python tool that get markdown docs and put then to gdscript as docs comments.

			Example of usage:
				md2gds_docs -o gds_source -ir md_source -s export.md

			Flags:
				-h, --help		will display this message
				-i, --input		you give dir sources of gdscript script to scan
				-r, --recursive		scan input recusivly
				-s, --skip		files and dirs to skip from input
			"""
		)
		exit()

	for i in args["input"]:
		scripts = scandir_for_gdscipts(
			i, args["recursive"], args["skip"]
		)
	
	gen_docs(scripts, args["output"])