import re, os, sys
from .print_debug import print_debug
from .bcolors import bcolors
from .color_message import color_message
from .comments_message import comments_message
from .bbcode_to_markdown import bbcode_to_markdown
from .add_comments_to_text import add_comments_to_text
from .print_text_tree import print_text_tree
from .snake_case_to_camel_case import snake_case_to_camel_case
from .add_arr_if_needed import add_arr_if_needed
from .prepare import prepare
from .md_tree import md_tree
from .write_to_md import write_to_md
from .get_argv_value import get_argv_value
from .get_argv import get_argv
from .lines_filter import lines_filter
from .infer_type import infer_type
from .gen_doc_for_var import gen_doc_for_var
from .gen_doc_for_const import gen_doc_for_const
from .gen_doc_for_signal import gen_doc_for_signal
from .gen_doc_for_func import gen_doc_for_func
from .gen_doc_for import gen_doc_for
from .check_gdsdoc import check_gdsdoc
from .gen_doc import gen_doc
from .gen_docs import gen_docs
from .scandir_for_gdscipts import scan_for_gdscripts

