import re, os, sys
from .scandir_for_gdscipts import scandir_for_gdscipts
from .gen_docs import gen_docs
from .gen_doc import gen_doc
from .write_to_md import write_to_md
from .add_arr_if_needed import add_arr_if_needed
from .prepare import prepare
from .bbcode_to_markdown import bbcode_to_markdown
from .add_comments_to_text import add_comments_to_text
from .md_tree import md_tree
from .print_text_tree import print_text_tree
from .parse_line import parse_line
from .color_message import color_message
from .comments_message import comments_message
from .gen_doc_for_var import gen_doc_for_var
from .gen_doc_for_const import gen_doc_for_const
from .gen_doc_for_signal import gen_doc_for_signal
from .gen_doc_for_func import gen_doc_for_func
from .print_debug import print_debug
from .gen_doc_for import gen_doc_for
from .get_argv_value import get_argv_value
from .get_argv import get_argv
from .snake_case_to_camel_case import snake_case_to_camel_case
from .lines_filter import lines_filter
from .bcolors import bcolors